/**
 * dtos.ts — Auto-generated by tools/generate_phase5.py
 *
 * One TS interface per WCF DTO in `MProgService.models`. Source data:
 *   reverse_engineering/metadata/MProgService.json (Phase 2)
 *
 * Optionality rule:
 *   • Property marked `[DataMember]` in the C# source ⇒ MANDATORY.
 *   • Property without `[DataMember]` (POCO-style)    ⇒ OPTIONAL (`name?: T`).
 * Some DTOs carry `[DataContract]` without `[DataMember]` on individual
 * properties; .NET treats those as serialized by the JSON formatter's
 * default (every public property). We still emit them as OPTIONAL so a
 * partial wire payload type-checks — Phase 5 doc §3 explains the
 * serialization-contract nuance.
 *
 * The `__source` const at the bottom is a compile-time witness of the
 * metadata file used to generate this — bump it manually if you ever
 * regenerate from a different binary.
 *
 * DO NOT EDIT MANUALLY — re-run `python3 tools/generate_phase5.py`.
 */

/* eslint-disable @typescript-eslint/no-explicit-any */

// ── Type aliases that match the wire shapes the WCF layer emits ───────
// `DateTime` arrives JSON-encoded by Newtonsoft.Json — by default that's an
// ISO-8601 string, but a Newtonsoft installation tuned for legacy serializers
// emits `"/Date(unix_ms)/"`. The interceptor in jwt_interceptor.ts treats
// these as opaque strings; if you ever need to parse, see Phase 5 §4.
export type WcfDateTime = string;

/** AccountBalanceInfo — 3 properties · 0/3 `[DataMember]` · [DataContract] */
export interface AccountBalanceInfo {
  /** .NET type: `Double` */
  balance?: number;
  /** .NET type: `String` */
  currencyname?: string;
  /** .NET type: `Double` */
  balancelocal?: number;
}

/** Accounts — 14 properties · 14/14 `[DataMember]` · [DataContract] · Oracle table hint: `data_acc` */
export interface Accounts {
  /** .NET type: `Int32` — `[DataMember]` */
  type: number;
  /** .NET type: `String` — `[DataMember]` */
  name: string;
  /** .NET type: `String` — `[DataMember]` */
  num: string;
  /** .NET type: `Double` — `[DataMember]` */
  mden: number;
  /** .NET type: `Double` — `[DataMember]` */
  dain: number;
  /** .NET type: `Double` — `[DataMember]` */
  balance: number;
  /** .NET type: `String` — `[DataMember]` */
  notblh: string;
  /** .NET type: `String` — `[DataMember]` */
  nomstlm: string;
  /** .NET type: `String` — `[DataMember]` */
  noadad: string;
  /** .NET type: `String` — `[DataMember]` */
  nog: string;
  /** .NET type: `String` — `[DataMember]` */
  tel: string;
  /** .NET type: `Int32` — `[DataMember]` */
  statH: number;
  /** .NET type: `String` — `[DataMember]` */
  namet: string;
  /** .NET type: `String` — `[DataMember]` */
  namep: string;
}

/** AccountsLedger — 9 properties · 9/9 `[DataMember]` · [DataContract] · Oracle table hint: `DATA_D` */
export interface AccountsLedger {
  /** .NET type: `Int32` — `[DataMember]` */
  Type: number;
  /** .NET type: `String` — `[DataMember]` */
  Notes: string;
  /** .NET type: `String` — `[DataMember]` */
  Num: string;
  /** .NET type: `Double` — `[DataMember]` */
  Mden: number;
  /** .NET type: `Double` — `[DataMember]` */
  Dain: number;
  /** .NET type: `Double` — `[DataMember]` */
  Balance: number;
  /** .NET type: `String` — `[DataMember]` */
  MDate: string;
  /** .NET type: `String` — `[DataMember]` */
  Pnum: string;
  /** .NET type: `String` — `[DataMember]` */
  Nref: string;
}

/** ChangePasswordRespons — 2 properties · 2/2 `[DataMember]` · [DataContract] */
export interface ChangePasswordRespons {
  /** .NET type: `Boolean` — `[DataMember]` */
  Success: boolean;
  /** .NET type: `String` — `[DataMember]` */
  Message: string;
}

/** RepBoxMovesDetals — 5 properties · 0/5 `[DataMember]` · POCO (no [DataContract]) · Oracle table hint: `SNDK_A` */
export interface RepBoxMovesDetals {
  /** .NET type: `String` */
  name?: string;
  /** .NET type: `String` */
  typems?: string;
  /** .NET type: `String` */
  nmstnd?: string;
  /** .NET type: `String` */
  notes?: string;
  /** .NET type: `String` */
  amount?: string;
}

/** RepBoxMoves — 6 properties · 0/6 `[DataMember]` · POCO (no [DataContract]) · Oracle table hint: `SNDK_A` */
export interface RepBoxMoves {
  /** .NET type: `String` */
  num?: string;
  /** .NET type: `String` */
  name?: string;
  /** .NET type: `String` */
  balance?: string;
  /** .NET type: `String` */
  mden?: string;
  /** .NET type: `String` */
  dain?: string;
  /** .NET type: `String` */
  fbalance?: string;
}

/** ServiceFault — 2 properties · 2/2 `[DataMember]` · [DataContract] */
export interface ServiceFault {
  /** .NET type: `String` — `[DataMember]` */
  ErrorCode: string;
  /** .NET type: `String` — `[DataMember]` */
  Message: string;
}

/** UserPlaces — 5 properties · 0/5 `[DataMember]` · POCO (no [DataContract]) · Oracle table hint: `USER_MNATK` */
export interface UserPlaces {
  /** .NET type: `String` */
  num?: string;
  /** .NET type: `String` */
  name?: string;
  /** .NET type: `String` */
  no_mstlm?: string;
  /** .NET type: `String` */
  RED?: string;
  /** .NET type: `String` */
  SDAD?: string;
}

/** RepReading — 3 properties · 0/3 `[DataMember]` · POCO (no [DataContract]) */
export interface RepReading {
  /** .NET type: `String` */
  num?: string;
  /** .NET type: `String` */
  name?: string;
  /** .NET type: `String` */
  ast?: string;
}

/** LPlaces — 2 properties · 0/2 `[DataMember]` · [DataContract] */
export interface LPlaces {
  /** .NET type: `String` */
  no?: string;
  /** .NET type: `String` */
  name?: string;
}

/** pGroup — 3 properties · 0/3 `[DataMember]` · POCO (no [DataContract]) · Oracle table hint: `GRP` */
export interface pGroup {
  /** .NET type: `String` */
  num?: string;
  /** .NET type: `String` */
  name?: string;
  /** .NET type: `String` */
  nomk2?: string;
}

/** plocation — 6 properties · 0/6 `[DataMember]` · POCO (no [DataContract]) · Oracle table hint: `Mkb2` */
export interface plocation {
  /** .NET type: `String` */
  num?: string;
  /** .NET type: `String` */
  name?: string;
  /** .NET type: `String` */
  no_mstlm?: string;
  /** .NET type: `String` */
  red?: string;
  /** .NET type: `String` */
  sdad?: string;
  /** .NET type: `System.Collections.Generic.List`1<MProgService.models.pGroup>` */
  GetListGroup?: unknown;
}

/** Grops — 2 properties · 0/2 `[DataMember]` · [DataContract] · Oracle table hint: `GRP` */
export interface Grops {
  /** .NET type: `String` */
  no?: string;
  /** .NET type: `String` */
  name?: string;
}

/** ListData — 2 properties · 0/2 `[DataMember]` · [DataContract] */
export interface ListData {
  /** .NET type: `String` */
  no?: string;
  /** .NET type: `String` */
  name?: string;
}

/** AuthData — 2 properties · 0/2 `[DataMember]` · [DataContract] */
export interface AuthData {
  /** .NET type: `String` */
  username?: string;
  /** .NET type: `String` */
  password?: string;
}

/** CompanyInfo — 4 properties · 0/4 `[DataMember]` · [DataContract] · Oracle table hint: `titl` */
export interface CompanyInfo {
  /** .NET type: `String` */
  compname?: string;
  /** .NET type: `String` */
  compaddress?: string;
  /** .NET type: `String` */
  compactive?: string;
  /** .NET type: `String` */
  comptelephone?: string;
}

/** Credentials — 3 properties · 0/3 `[DataMember]` · POCO (no [DataContract]) */
export interface Credentials {
  /** .NET type: `String` */
  User?: string;
  /** .NET type: `String` */
  Password?: string;
  /** .NET type: `String` */
  appId?: string;
}

/** Currency — 4 properties · 4/4 `[DataMember]` · [DataContract] · Oracle table hint: `amlh` */
export interface Currency {
  /** .NET type: `String` — `[DataMember]` */
  name: string;
  /** .NET type: `String` — `[DataMember]` */
  num: string;
  /** .NET type: `String` — `[DataMember]` */
  fls: string;
  /** .NET type: `Double` — `[DataMember]` */
  sars: number;
}

/** ItemReading — 17 properties · 17/17 `[DataMember]` · [DataContract] · Oracle table hint: `DATA_M` */
export interface ItemReading {
  /** .NET type: `String` — `[DataMember]` */
  name: string;
  /** .NET type: `String` — `[DataMember]` */
  namet: string;
  /** .NET type: `String` — `[DataMember]` */
  notblh: string;
  /** .NET type: `String` — `[DataMember]` */
  ind: string;
  /** .NET type: `String` — `[DataMember]` */
  nomstlm: string;
  /** .NET type: `String` — `[DataMember]` */
  noadad: string;
  /** .NET type: `String` — `[DataMember]` */
  num: string;
  /** .NET type: `String` — `[DataMember]` */
  nog: string;
  /** .NET type: `String` — `[DataMember]` */
  ks: string;
  /** .NET type: `String` — `[DataMember]` */
  kh: string;
  /** .NET type: `String` — `[DataMember]` */
  cas: string;
  /** .NET type: `String` — `[DataMember]` */
  asts: string;
  /** .NET type: `String` — `[DataMember]` */
  sk: string;
  /** .NET type: `String` — `[DataMember]` */
  mt: string;
  /** .NET type: `String` — `[DataMember]` */
  kmsn: string;
  /** .NET type: `String` — `[DataMember]` */
  matm33: string;
  /** .NET type: `String` — `[DataMember]` */
  rtrdn: string;
}

/** ItemBonds — 19 properties · 19/19 `[DataMember]` · [DataContract] · Oracle table hint: `DATA_D` */
export interface ItemBonds {
  /** .NET type: `Int32` — `[DataMember]` */
  type: number;
  /** .NET type: `String` — `[DataMember]` */
  name: string;
  /** .NET type: `String` — `[DataMember]` */
  name_s: string;
  /** .NET type: `String` — `[DataMember]` */
  nmstnd: string;
  /** .NET type: `String` — `[DataMember]` */
  notes: string;
  /** .NET type: `String` — `[DataMember]` */
  notes2: string;
  /** .NET type: `String` — `[DataMember]` */
  num: string;
  /** .NET type: `String` — `[DataMember]` */
  num_s: string;
  /** .NET type: `Double` — `[DataMember]` */
  mden: number;
  /** .NET type: `Double` — `[DataMember]` */
  dain: number;
  /** .NET type: `Double` — `[DataMember]` */
  balance: number;
  /** .NET type: `String` — `[DataMember]` */
  mdate: string;
  /** .NET type: `Double` — `[DataMember]` */
  price_trans: number;
  /** .NET type: `String` — `[DataMember]` */
  notes_box: string;
  /** .NET type: `String` — `[DataMember]` */
  cas: string;
  /** .NET type: `String` — `[DataMember]` */
  currencyid: string;
  /** .NET type: `String` — `[DataMember]` */
  currencyname: string;
  /** .NET type: `MProgService.models.Currency` — `[DataMember]` */
  currency: unknown;
  /** .NET type: `MProgService.models.Accounts` — `[DataMember]` */
  account: unknown;
}

/** RepBalanceDetails — 10 properties · 10/10 `[DataMember]` · [DataContract] */
export interface RepBalanceDetails {
  /** .NET type: `String` — `[DataMember]` */
  type: string;
  /** .NET type: `String` — `[DataMember]` */
  nmstnd: string;
  /** .NET type: `String` — `[DataMember]` */
  notes: string;
  /** .NET type: `String` — `[DataMember]` */
  num: string;
  /** .NET type: `Double` — `[DataMember]` */
  mden: number;
  /** .NET type: `Double` — `[DataMember]` */
  dain: number;
  /** .NET type: `Double` — `[DataMember]` */
  balance: number;
  /** .NET type: `String` — `[DataMember]` */
  mdate: string;
  /** .NET type: `String` — `[DataMember]` */
  pnum: string;
  /** .NET type: `String` — `[DataMember]` */
  nref: string;
}

/** RepBalanceHeader — 12 properties · 12/12 `[DataMember]` · [DataContract] */
export interface RepBalanceHeader {
  /** .NET type: `String` — `[DataMember]` */
  name: string;
  /** .NET type: `Int32` — `[DataMember]` */
  type: number;
  /** .NET type: `String` — `[DataMember]` */
  notes: string;
  /** .NET type: `String` — `[DataMember]` */
  num: string;
  /** .NET type: `Double` — `[DataMember]` */
  smden: number;
  /** .NET type: `Double` — `[DataMember]` */
  sdain: number;
  /** .NET type: `Double` — `[DataMember]` */
  mden: number;
  /** .NET type: `Double` — `[DataMember]` */
  dain: number;
  /** .NET type: `Double` — `[DataMember]` */
  balance: number;
  /** .NET type: `String` — `[DataMember]` */
  mdate: string;
  /** .NET type: `String` — `[DataMember]` */
  pnum: string;
  /** .NET type: `String` — `[DataMember]` */
  nref: string;
}

/** RepBondsHeader — 12 properties · 12/12 `[DataMember]` · [DataContract] */
export interface RepBondsHeader {
  /** .NET type: `String` — `[DataMember]` */
  name: string;
  /** .NET type: `Int32` — `[DataMember]` */
  type: number;
  /** .NET type: `String` — `[DataMember]` */
  notes: string;
  /** .NET type: `String` — `[DataMember]` */
  num: string;
  /** .NET type: `Double` — `[DataMember]` */
  smden: number;
  /** .NET type: `Double` — `[DataMember]` */
  sdain: number;
  /** .NET type: `Double` — `[DataMember]` */
  mden: number;
  /** .NET type: `Double` — `[DataMember]` */
  dain: number;
  /** .NET type: `Double` — `[DataMember]` */
  balance: number;
  /** .NET type: `String` — `[DataMember]` */
  mdate: string;
  /** .NET type: `String` — `[DataMember]` */
  currencyid: string;
  /** .NET type: `String` — `[DataMember]` */
  currencyname: string;
}

/** DataComp — 4 properties · 4/4 `[DataMember]` · [DataContract] */
export interface DataComp {
  /** .NET type: `String` — `[DataMember]` */
  compname: string;
  /** .NET type: `String` — `[DataMember]` */
  compaddress: string;
  /** .NET type: `String` — `[DataMember]` */
  comptelephone: string;
  /** .NET type: `String` — `[DataMember]` */
  compactive: string;
}

/** ResultPost — 4 properties · 4/4 `[DataMember]` · [DataContract] */
export interface ResultPost {
  /** .NET type: `String` — `[DataMember]` */
  Result: string;
  /** .NET type: `String` — `[DataMember]` */
  StatusCode: string;
  /** .NET type: `String` — `[DataMember]` */
  Error_msg: string;
  /** .NET type: `Double` — `[DataMember]` */
  Balance: number;
}

/** Token — 3 properties · 0/3 `[DataMember]` · POCO (no [DataContract]) */
export interface Token {
  /** .NET type: `System.DateTime` */
  CreateDate?: unknown;
  /** .NET type: `Int32` */
  UserId?: number;
  /** .NET type: `String` */
  token?: string;
}

/** Users — 15 properties · 15/15 `[DataMember]` · [DataContract] · Oracle table hint: `USER_R` */
export interface Users {
  /** .NET type: `Int32` — `[DataMember]` */
  NOU: number;
  /** .NET type: `String` — `[DataMember]` */
  NAME_U: string;
  /** .NET type: `Int32` — `[DataMember]` */
  NOA: number;
  /** .NET type: `Int32` — `[DataMember]` */
  ED: number;
  /** .NET type: `Int32` — `[DataMember]` */
  DE: number;
  /** .NET type: `Int32` — `[DataMember]` */
  S_K: number;
  /** .NET type: `Int32` — `[DataMember]` */
  S_S: number;
  /** .NET type: `Int32` — `[DataMember]` */
  REP: number;
  /** .NET type: `Int32` — `[DataMember]` */
  SYS: number;
  /** .NET type: `String` — `[DataMember]` */
  PASS: string;
  /** .NET type: `String` — `[DataMember]` */
  access_token: string;
  /** .NET type: `String` — `[DataMember]` */
  version: string;
  /** .NET type: `Int32` — `[DataMember]` */
  error_no: number;
  /** .NET type: `String` — `[DataMember]` */
  error_msg: string;
  /** .NET type: `String` — `[DataMember]` */
  date_server: string;
}

export type DtoName =
  | "AccountBalanceInfo"
  | "Accounts"
  | "AccountsLedger"
  | "ChangePasswordRespons"
  | "RepBoxMovesDetals"
  | "RepBoxMoves"
  | "ServiceFault"
  | "UserPlaces"
  | "RepReading"
  | "LPlaces"
  | "pGroup"
  | "plocation"
  | "Grops"
  | "ListData"
  | "AuthData"
  | "CompanyInfo"
  | "Credentials"
  | "Currency"
  | "ItemReading"
  | "ItemBonds"
  | "RepBalanceDetails"
  | "RepBalanceHeader"
  | "RepBondsHeader"
  | "DataComp"
  | "ResultPost"
  | "Token"
  | "Users";

export const __source = {
  metadata: "reverse_engineering/metadata/MProgService.json",
  phase: 5,
  count: 27,
} as const;
