#!/usr/bin/env python3
"""
05_generate_typescript.py
-------------------------
Read the decompiled C# under reverse_engineering/decompiled_csharp/MProgService
and emit TypeScript interfaces into api_contracts/typescript_types.ts.

This script is **populated in Phase 5**. For Phase 1 we only check that the
decompile directory is present and emit a single placeholder block so the
file pipeline is wired correctly.

Idempotent — safe to re-run.
"""
from __future__ import annotations

import re
import sys
import argparse
from pathlib import Path

REPO = Path(__file__).resolve().parent.parent
DECOMP_DIR = REPO / "reverse_engineering" / "decompiled_csharp" / "MProgService"
OUT_FILE   = REPO / "api_contracts" / "typescript_types.ts"

CS_TO_TS: dict[str, str] = {
    "int":      "number",
    "Int32":    "number",
    "long":     "number",
    "Int64":    "number",
    "short":    "number",
    "byte":     "number",
    "double":   "number",
    "float":    "number",
    "decimal":  "number",
    "bool":     "boolean",
    "Boolean":  "boolean",
    "string":   "string",
    "String":   "string",
    "DateTime": "string",  # serialised as ISO-8601 by Json.NET
    "Guid":     "string",
    "object":   "unknown",
    "byte[]":   "string",  # base64
}

PROP_RX = re.compile(
    r"public\s+(?P<type>[\w\.<>\[\]\?,\s]+?)\s+(?P<name>\w+)\s*{\s*get;\s*set;\s*}"
)


def cs_to_ts(t: str) -> str:
    t = t.strip()
    nullable = t.endswith("?")
    if nullable:
        t = t[:-1]
    if t.startswith("List<") or t.startswith("IEnumerable<"):
        inner = t.split("<", 1)[1].rsplit(">", 1)[0]
        return f"{cs_to_ts(inner)}[]" + (" | null" if nullable else "")
    if t.endswith("[]"):
        return f"{cs_to_ts(t[:-2])}[]" + (" | null" if nullable else "")
    return CS_TO_TS.get(t, t) + (" | null" if nullable else "")


def extract_models(root: Path) -> list[tuple[str, list[tuple[str, str]]]]:
    models: list[tuple[str, list[tuple[str, str]]]] = []
    if not root.exists():
        return models
    for cs in root.rglob("*.cs"):
        text = cs.read_text(errors="ignore")
        # Find `class Foo` blocks
        for m in re.finditer(r"class\s+(\w+)\b[^{]*\{", text):
            cls_name = m.group(1)
            # crude: take content up to the next top-level closing brace.
            body = text[m.end(): m.end() + 4000]
            props = [(p.group("name"), p.group("type"))
                     for p in PROP_RX.finditer(body)]
            if props:
                models.append((cls_name, props))
    return models


def emit(models: list[tuple[str, list[tuple[str, str]]]]) -> str:
    out = [
        "// AUTOGENERATED — DO NOT EDIT BY HAND",
        "// Source: reverse_engineering/decompiled_csharp/MProgService",
        "// Run: python3 tools/05_generate_typescript.py",
        "",
    ]
    if not models:
        out += [
            "// (No models extracted yet — run Phase 2 first to produce the",
            "//  decompiled C# under reverse_engineering/decompiled_csharp/.)",
            "export {};",
            "",
        ]
        return "\n".join(out)
    for name, props in models:
        out.append(f"export interface {name} {{")
        for pname, ptype in props:
            out.append(f"  {pname}: {cs_to_ts(ptype)};")
        out.append("}")
        out.append("")
    return "\n".join(out)


def main() -> int:
    ap = argparse.ArgumentParser()
    ap.add_argument("--dry-run", action="store_true")
    args = ap.parse_args()

    models = extract_models(DECOMP_DIR)
    rendered = emit(models)

    if args.dry_run:
        sys.stdout.write(rendered)
        return 0

    OUT_FILE.parent.mkdir(parents=True, exist_ok=True)
    OUT_FILE.write_text(rendered)
    print(f"[ts] wrote {OUT_FILE.relative_to(REPO)} ({len(models)} models)")
    return 0


if __name__ == "__main__":
    raise SystemExit(main())
